### ISSUE TITLE
Broken dependency on k8s.io/kubelet v0.0.0

### ISSUE THREAD

**Issue by jamie-digital** [vdemeester/k8s-pkg-credentialprovider#11]
Hi!

As of v1.21.0, `go.mod` requires `k8s.io/kubelet v0.0.0`, which isn't a valid version. This is fine when building the module directly, as the replacement `k8s.io/kubelet => k8s.io/kubelet v0.21.0` uses a valid version instead. Unfortunately, when a module is used as a dependency, [its replace directives are ignored](https://golang.org/ref/mod#go-mod-file-replace).

As a result, trying to update to v1.21.0 gives the following error:

```
go: downloading github.com/vdemeester/k8s-pkg-credentialprovider v1.21.0
go get: github.com/vdemeester/k8s-pkg-credentialprovider@v1.19.7 updating to
	github.com/vdemeester/k8s-pkg-credentialprovider@v1.21.0 requires
	k8s.io/kubelet@v0.0.0: reading k8s.io/kubelet/go.mod at revision v0.0.0: unknown revision v0.0.0
```

Would it be possible to use `k8s.io/kubelet v0.21.0` in the require directive instead of using a replace directive?

**Comment by vdemeester** [comment]
@jamie-digital [`v1.21.0-1`](https://github.com/vdemeester/k8s-pkg-credentialprovider/tree/v1.21.0-1) should fix it 👼🏼

**Comment by jamie-digital** [comment]
@vdemeester it does indeed! Thanks for such a quick turn-around! 😁
